name: Tests

on: [push]

jobs:
  build:
    name: PHP ${{ matrix.php-version }}-${{ matrix.os }}
    env:
      extensions: apc, curl, mbstring, dom, intl, mysql, pgsql, pdo, pdo_sqlite, imagick
      key: cache-v1

    runs-on: ${{ matrix.os }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: myUser
          MYSQL_PASSWORD: myPass
          MYSQL_DATABASE: myDB
          MYSQL_ROOT_PASSWORD: myPass
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php-version:
          - "7.4"
          - "8.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
